#!/bin/bash

print_usage_exit () {
    echo "Usage:"
    echo "  $0 start"
    echo "  $0 stop"
    echo "  $0 status"
    exit 1
}

stream_start () {
    if pgrep mjpg_streamer > /dev/null; then
        echo "Already started"
        exit 1
    fi

    cd /home/pi/mjpg-streamer/mjpg-streamer-experimental

    ./mjpg_streamer -i "./input_raspicam.so -fps 5 -hf -vf -quality 10 -x 400 -y 300" -o "./output_http.so" &
    # if you want password protection: ..... "./output_http.so -w ./www -c username:password"
}

stream_stop () {
    pkill mjpg_streamer
}

stream_status () {
    if ps aux --width=500 | grep mjpg_streamer | grep -v " grep "; then
        exit 0
    else
        echo Stopped
        exit 1
    fi
}

if ! test $1; then
    print_usage_exit
fi

if test $1 = "start"; then
    stream_start
elif test $1 = "stop"; then
    stream_stop
elif test $1 = "status"; then
    stream_status
else
    print_usage_exit
fi
